// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWvKNhFQocXTLD16zfPQQ4HXNEm-kUALw',
    appId: '1:139646970928:web:a8ab75acb0eb381f21d1f5',
    messagingSenderId: '139646970928',
    projectId: 'vc-base-service',
    authDomain: 'vc-base-service.firebaseapp.com',
    storageBucket: 'vc-base-service.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATkCEMLcTLdd07Dz9EUbU7vl22Yq4NEko',
    appId: '1:139646970928:android:04b54fc7be3faf8f21d1f5',
    messagingSenderId: '139646970928',
    projectId: 'vc-base-service',
    storageBucket: 'vc-base-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBB7PEv1mAKnkInh6XwbjpFvj4jTXIUmg',
    appId: '1:139646970928:ios:f623c21478bd4b5221d1f5',
    messagingSenderId: '139646970928',
    projectId: 'vc-base-service',
    storageBucket: 'vc-base-service.firebasestorage.app',
    iosBundleId: 'com.example.baseService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBB7PEv1mAKnkInh6XwbjpFvj4jTXIUmg',
    appId: '1:139646970928:ios:f623c21478bd4b5221d1f5',
    messagingSenderId: '139646970928',
    projectId: 'vc-base-service',
    storageBucket: 'vc-base-service.firebasestorage.app',
    iosBundleId: 'com.example.baseService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWvKNhFQocXTLD16zfPQQ4HXNEm-kUALw',
    appId: '1:139646970928:web:068cd5acf1a6ea1d21d1f5',
    messagingSenderId: '139646970928',
    projectId: 'vc-base-service',
    authDomain: 'vc-base-service.firebaseapp.com',
    storageBucket: 'vc-base-service.firebasestorage.app',
  );
}
